/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.felipemdf.investmais.ui;

import com.felipemdf.investmais.ui.screen.lancamento.LancamentoPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author fmari_v4rpu9g
 */
public class InvestMaisFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvestMaisFrame
     */
    public InvestMaisFrame() {
        initComponents();
        
        setup();
        
        tabbedPane.add("Lançamentos", new LancamentoPanel());
        
    }
    
    private void setup() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(1280, 720);
        this.setPreferredSize(new Dimension(1280,720));
        this.setMinimumSize(new Dimension(1280,720));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        labelCarteira = new javax.swing.JLabel();
        carteira = new javax.swing.JLabel();
        labelValorAplicado = new javax.swing.JLabel();
        valorAplicado = new javax.swing.JLabel();
        labelSaldoBruto = new javax.swing.JLabel();
        saldoBruto = new javax.swing.JLabel();
        labelVariacao = new javax.swing.JLabel();
        variacao = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        labelCarteira.setText("CARTEIRA");

        carteira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carteira.setText("Minha Carteira");

        labelValorAplicado.setText("VALOR APLICADO");

        valorAplicado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valorAplicado.setText("R$ 995,70");

        labelSaldoBruto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSaldoBruto.setText("R$ 991,02");

        saldoBruto.setText("SALDO BRUTO");

        labelVariacao.setText("VARIAÇÃO");

        variacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        variacao.setText("-0,47%");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCarteira)
                    .addComponent(carteira))
                .addGap(113, 113, 113)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValorAplicado)
                    .addComponent(valorAplicado))
                .addGap(32, 32, 32)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoBruto)
                    .addComponent(labelSaldoBruto))
                .addGap(32, 32, 32)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVariacao)
                    .addComponent(variacao))
                .addContainerGap(1292, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(labelCarteira)
                        .addGap(2, 2, 2)
                        .addComponent(carteira))
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addComponent(saldoBruto)
                            .addGap(2, 2, 2)
                            .addComponent(labelSaldoBruto))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addComponent(labelValorAplicado)
                            .addGap(2, 2, 2)
                            .addComponent(valorAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                            .addComponent(labelVariacao)
                            .addGap(2, 2, 2)
                            .addComponent(variacao))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvestMaisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvestMaisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvestMaisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvestMaisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvestMaisFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carteira;
    private javax.swing.JLabel labelCarteira;
    private javax.swing.JLabel labelSaldoBruto;
    private javax.swing.JLabel labelValorAplicado;
    private javax.swing.JLabel labelVariacao;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JLabel saldoBruto;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel valorAplicado;
    private javax.swing.JLabel variacao;
    // End of variables declaration//GEN-END:variables
}
